# Generated by Django 4.0.5 on 2022-06-18 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketmessage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='reply_to',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticketmessage'
            ),
        ),
    ]
